### ISSUE TITLE
requerements are huge - not usable on a pi or mk1

### ISSUE THREAD

**Issue by andlo** [JarbasAl/skill-good-manners#1]
The requerements for this skill are huge….not capable for picroft or mk1. When installing lots of stuff needs to be compiled, and my mk1 couldnt make it. 

Maybe there is a way to have lessor dependencies or something….

But the skill idea and skill itself do look nice.

the requerement https://github.com/nguyentr17/Insults has these requerements:
```
boto3==1.4.7
flake8==2.3.0
futures==2.2.0
keras==2.0.5
matplotlib==2.0.0
mock==2.0.0
nltk==3.0
pandas==0.19.2
pyparsing==1.5.6
python-dateutil==2.4.1
pytest==3.0.6
Pytz==2017.2
six==1.10.0
tensorflow==1.0.0
```

**Comment by JarbasAl** [comment]
hum, those were supposed to be optional, my bad

the skill actually has a mode (default) to not use those for this reason, i forgot to remove from requirements

**Comment by andlo** [comment]
Ohh great. Then it isnt an issue :) Ill test more.

**Comment by JarbasAl** [comment]
renamed file so it wont auto install, will add logic in skill itself to install those if requested, and not allow in a pi
